heat_template_version: newton

description:
    Ubuntu servers for OpenStack installation.

resources:
  network-services:
    type: "OS::Nova::Server"
    properties:
      flavor: 1 GB General Purpose v1
      image: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
      key_name: mykey
      name: network-services
      networks:
        - network: 00000000-0000-0000-0000-000000000000
        - network: 11111111-1111-1111-1111-111111111111
        - network: management
        - network: external

  controller:
    type: "OS::Nova::Server"
    properties:
      flavor: 8 GB General Purpose v1
      image: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
      name: controller
      admin_pass: stack
      networks:
        - network: management
        - network: internal
        - network: external

  compute:
    type: "OS::Nova::Server"
    properties:
      flavor: 8 GB General Purpose v1
      image: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
      name: compute
      admin_pass: stack
      networks:
        - network: management
        - network: internal
        - network: external

  block:
    type: "OS::Nova::Server"
    properties:
      flavor: 4 GB General Purpose v1
      image: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
      name: block
      admin_pass: stack
      networks:
        - network: management
        - network: internal

  block1:
    type: OS::Cinder::Volume
    properties:
      size: 75

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: block1 }
      instance_uuid: { get_resource: block }
